# Generated by Django 4.2.24 on 2025-09-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_telefon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='lavozim',
            field=models.CharField(default='talaba', max_length=100, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sharif',
            field=models.CharField(max_length=100, verbose_name='Sharif'),
        ),
    ]
