# Generated by Django 4.2.24 on 2025-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_lavozim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lavozim',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Talaba', 'Talaba')], default='Talaba', max_length=20, verbose_name='Rol'),
        ),
    ]
