# Generated by Django 4.2.16 on 2024-09-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fayl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('fan', models.CharField(max_length=100)),
                ('pasport', models.FileField(upload_to='pasportlar/')),
                ('diplom', models.FileField(upload_to='diplomlar/')),
                ('ariza', models.FileField(blank=True, upload_to='ariza/')),
                ('malumotnoma', models.FileField(upload_to='malumotnoma/')),
                ('anketa', models.FileField(upload_to='minimum anketa/')),
                ('kochirma', models.FileField(upload_to='kengash ko`chirmasi/')),
                ('royhat', models.FileField(upload_to='ilmiy ishlar ro`yati/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Namuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom', models.FileField(upload_to='namuna/')),
                ('ariza', models.FileField(upload_to='namuna/')),
                ('malumotnoma', models.FileField(upload_to='namuna/')),
                ('anketa', models.FileField(upload_to='namuna/')),
                ('kochirma', models.FileField(upload_to='namuna/')),
                ('royhat', models.FileField(upload_to='namuna/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
                ('oy', models.IntegerField()),
                ('kun', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
