# Generated by Django 4.2.24 on 2025-09-19 14:07

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fayl',
            options={'ordering': ['-sana'], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterField(
            model_name='fayl',
            name='anketa',
            field=models.FileField(upload_to='minimum_anketa/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'wps']), files.models.validate_file_size], verbose_name='Minimum anketasi'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='ariza',
            field=models.FileField(blank=True, upload_to='ariza/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'wps']), files.models.validate_file_size], verbose_name="Ariza yoki yo'llanma xat"),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='diplom',
            field=models.FileField(upload_to='diplomlar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'wps']), files.models.validate_file_size], verbose_name='Diplomlar'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='familya',
            field=models.CharField(max_length=100, verbose_name='Familya'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='fan',
            field=models.CharField(choices=[('uzbek_tili', "O'zbek tili"), ('til_nazariyasi', 'Til nazariyasi. Amaliy va kompyuter lingvistikasi'), ('talim_tarbiya', "Ta'lim va tarbiya nazariyasi va metodikasi(ijtimoiy-gumanitar fanlar)"), ('ingliz_tili', 'Chet tili (Ingliz tili)'), ('nemis_tili', 'Chet tili (Nemis tili)')], max_length=50, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='kochirma',
            field=models.FileField(upload_to='kengash_kochirmasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'wps']), files.models.validate_file_size], verbose_name="Kengash qarori ko'chirmasi"),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='malumotnoma',
            field=models.FileField(upload_to='malumotnoma/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'wps']), files.models.validate_file_size], verbose_name="Ma'lumotnoma"),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='pasport',
            field=models.FileField(upload_to='pasportlar/', validators=[files.models.validate_file_size], verbose_name='Pasport nusxasi'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='royhat',
            field=models.FileField(upload_to='ilmiy_ishlar_royxati/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'wps']), files.models.validate_file_size], verbose_name="Ilmiy ishlar ro'yxati"),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana'),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='telefon',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998[0-9]{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
