# Generated by Django 4.1.7 on 2023-03-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasport', models.FileField(upload_to='pasportlar/')),
                ('diplom', models.FileField(upload_to='diplomlar/')),
                ('ariza', models.FileField(upload_to='ariza/')),
                ('malumotnoma', models.FileField(upload_to='malumotnoma/')),
                ('anketa', models.FileField(upload_to='minimum anketa/')),
                ('kochirma', models.FileField(upload_to='kengash ko`chirmasi/')),
                ('yollanma', models.FileField(upload_to='yo`lanma xat/')),
                ('royhat', models.FileField(upload_to='ilmiy ishlar ro`yati/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
                ('oy', models.IntegerField()),
                ('kun', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
