# Generated by Django 4.1.7 on 2023-03-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_namuna_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namuna',
            name='anketa',
            field=models.FileField(upload_to='namuna/'),
        ),
        migrations.AlterField(
            model_name='namuna',
            name='ariza',
            field=models.FileField(upload_to='namuna/'),
        ),
        migrations.AlterField(
            model_name='namuna',
            name='diplom',
            field=models.FileField(upload_to='namuna/'),
        ),
        migrations.AlterField(
            model_name='namuna',
            name='kochirma',
            field=models.FileField(upload_to='namuna/'),
        ),
        migrations.AlterField(
            model_name='namuna',
            name='malumotnoma',
            field=models.FileField(upload_to='namuna/'),
        ),
        migrations.AlterField(
            model_name='namuna',
            name='pasport',
            field=models.FileField(upload_to='namuna/'),
        ),
        migrations.AlterField(
            model_name='namuna',
            name='royhat',
            field=models.FileField(upload_to='namuna/'),
        ),
        migrations.AlterField(
            model_name='namuna',
            name='yollanma',
            field=models.FileField(upload_to='namuna/'),
        ),
    ]
