# Generated by Django 4.2.24 on 2025-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_fayl_options_alter_fayl_anketa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(default='Ariza yuborish muddati', max_length=200, verbose_name='Deadline nomi')),
                ('deadline_sana', models.DateTimeField(verbose_name='Tugash sana va vaqti')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('yangilangan', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlinelar',
                'ordering': ['-yaratilgan'],
            },
        ),
    ]
