# Generated by Django 4.1.7 on 2023-03-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_namuna_anketa_alter_namuna_ariza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namuna',
            name='pasport',
        ),
        migrations.RemoveField(
            model_name='namuna',
            name='yollanma',
        ),
    ]
