# Generated by Django 4.2.24 on 2025-09-20 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanYonalishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name="To'liq nomi")),
                ('belgilangan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Belgilangan sana')),
            ],
            options={
                'verbose_name': "Fan yo'nalishi",
                'verbose_name_plural': "Fan yo'nalishlari",
            },
        ),
        migrations.RemoveField(
            model_name='fayl',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='fayl',
            name='familya',
        ),
        migrations.RemoveField(
            model_name='fayl',
            name='ism',
        ),
        migrations.AddField(
            model_name='fayl',
            name='fan_yonalishi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fayllar', to='files.fanyonalishi', verbose_name="Fan yo'nalishi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fayl',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fayllar', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
            preserve_default=False,
        ),
    ]