# Generated by Django 4.1.7 on 2023-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_namuna_pasport_remove_namuna_yollanma'),
    ]

    operations = [
        migrations.AddField(
            model_name='fayl',
            name='telefon',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
