# Generated by Django 4.1.7 on 2023-04-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_fayl_ariza_alter_fayl_yollanma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fayl',
            name='yollanma',
        ),
    ]
